#/// localhost
### Monsters
### Get All monsters
GET  http://localhost:3000/monsters

### Get Monster by ID
GET  http://localhost:3000/monsters/67f15ad91745002f3dabfb8a

### Create Monster
POST  http://localhost:3000/monsters http/1.1
Content-Type: application/json

{
    "name": "Mizutsune",
    "elementWeakness": "thunder",
    "weakSpot": "head",
    "damageTypeWeak": "slash",
    "type": "Leviathan"
}

### Update Monster
PUT http://localhost:3000/monsters/67f15adf1745002f3dabfb8b
Content-Type: application/json

{
    "name": "Rathian",
    "elementWeakness": "dragon",
    "weakSpot": "head",
    "damageTypeWeak": "impact",
    "type": "Flying Wyvern"
}

### Delete a Monster
DELETE http://localhost:3000/monsters/67f15a581745002f3dabfb89

### Weapons

### Get All weapons
GET  http://localhost:3000/weapons

### Get weapon by ID
GET  http://localhost:3000/weapons/67f161717372f6b9f9e46d50

### Create weapon
POST  http://localhost:3000/weapons http/1.1
Content-Type: application/json

{
    "name": "Ajara-Jivaka",
    "elementType": "blast",
    "elementValue": 250,
    "damageType": "impact",
    "attackValue": 210,
    "weaponType": "hunting horn"
}

### Update weapon
PUT http://localhost:3000/weapons/67f161747372f6b9f9e46d51
Content-Type: application/json

{
    "name": "Poison Blade II",
    "elementType": "poison",
    "elementValue": 290,
    "damageType": "slash",
    "attackValue": 200,
    "weaponType": "charge blade"
}

### Delete a weapon
DELETE http://localhost:3000/weapons/67f162b6adb83e11159a3135